
-- Main
hook_event(HOOK_MARIO_UPDATE, CLIENT_UPDATING)
-- Co-op
hook_event(HOOK_ALLOW_PVP_ATTACK, COOP_ACTION_CHECK)
hook_event(HOOK_ON_SET_MARIO_ACTION, ALLOW_COOP_ACTION)
-- Action
hook_mario_action(ACT_PRESSED_DISALLOWED, DISALLOWED_ACTION)